import { NavLink } from "react-router-dom";
import { Download, Sparkles } from "lucide-react";
import { sidebarItems } from "../config/navigation";
import { useTrip } from "../context/TripContext";
import { formatINR } from "../utils/currency";

function Sidebar() {
  const { trip } = useTrip();

  const handleDownload = () => {
    if (!trip.flight) {
      alert("Please generate a trip plan first!");
      return;
    }

    const lines = [
      `====================================`,
      `   AI TRAVEL PLAN`,
      `====================================`,
      `${trip.source} → ${trip.destination} | ${trip.days} Days`,
      ``,
      `------------------------------------`,
      `FLIGHT DETAILS`,
      `------------------------------------`,
      `Airline: ${trip.flight?.airline || "N/A"}`,
      `Flight: ${trip.flight?.flightNumber || "N/A"} | ${trip.flight?.aircraft || "N/A"}`,
      `Departure: ${trip.flight?.departureTime || "N/A"} from ${trip.flight?.departureAirport || "N/A"}`,
      `Arrival: ${trip.flight?.arrivalTime || "N/A"} at ${trip.flight?.arrivalAirport || "N/A"}`,
      `Duration: ${trip.flight?.duration || "N/A"} | ${trip.flight?.stops || "Non-stop"}`,
      `Price: ${formatINR(trip.flight?.priceInr || 0)} per person`,
      ``,
      `------------------------------------`,
      `HOTEL OPTIONS`,
      `------------------------------------`,
      ...(trip.hotels || []).map(h =>
        `${h.tag}: ${h.name} | ${formatINR(h.pricePerNightInr)}/night | ${h.rating}★ | ${h.location}`
      ),
      ``,
      `------------------------------------`,
      `WEATHER FORECAST`,
      `------------------------------------`,
      `City: ${trip.weather?.city}, ${trip.weather?.country}`,
      `Average High: ${trip.weather?.avgHigh}°C | Average Low: ${trip.weather?.avgLow}°C`,
      `Overall: ${trip.weather?.overallCondition}`,
      ...(trip.weather?.daily || []).map(d =>
        `${d.day}: ${d.min}°C - ${d.max}°C, ${d.condition}`
      ),
      ``,
      `------------------------------------`,
      `BUDGET BREAKDOWN`,
      `------------------------------------`,
      ...(trip.budget?.categories || []).map(c =>
        `${c.name}: ${formatINR(c.amountInr)} (${c.percentage}%)`
      ),
      `Total: ${formatINR(trip.budget?.totalInr || 0)}`,
      ``,
      `------------------------------------`,
      `DAY-BY-DAY ITINERARY`,
      `------------------------------------`,
      ...(trip.itinerary || []).flatMap(day => [
        ``,
        `Day ${day.day}: ${day.title}`,
        ...(day.activities || []).map(a => `  • ${a}`),
        `  Tip: ${day.tip}`,
      ]),
      ``,
      `====================================`,
      `Generated by AI Travel Planner`,
      `====================================`,
    ];

    const content = lines.join("\n");
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${trip.source}-to-${trip.destination}-travel-plan.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <aside className="bg-slate-950 shrink-0 text-white flex flex-col w-60 h-full">
      <div className="p-4 flex flex-col gap-1 flex-1 overflow-y-auto">
        <span className="font-semibold uppercase text-white/40 text-xs leading-4 tracking-wider px-3 py-2">
          Menu
        </span>

        <nav className="flex flex-col gap-1">
          {sidebarItems.map((item) => {
            const Icon = item.icon;
            return (
              <NavLink
                key={item.label}
                to={item.path}
                end={item.end}
                className={({ isActive }) =>
                  `font-medium rounded-lg text-sm leading-5 flex px-3 py-2.5 items-center gap-3 transition-colors ${
                    isActive
                      ? "bg-blue-500 text-white font-semibold"
                      : "text-white/70 hover:text-white hover:bg-white/5"
                  }`
                }
              >
                <Icon className="size-4" />
                {item.label}
              </NavLink>
            );
          })}
        </nav>
      </div>

      <div className="p-4 flex flex-col gap-2 border-t border-white/10">
        <div className="rounded-xl bg-white/5 p-4">
          <div className="text-white/90 flex items-center gap-2">
            <Sparkles className="size-4 text-blue-400" />
            <span className="font-semibold text-sm leading-5">Trip Ready</span>
          </div>
          <p className="text-white/50 text-xs leading-4 mt-1">
            {trip.generated
              ? `${trip.source} → ${trip.destination} · ${trip.days} days`
              : "Plan a trip to get started"}
          </p>
        </div>

        <button
          type="button"
          onClick={handleDownload}
          className="font-medium rounded-lg text-white/70 text-sm leading-5 flex px-3 py-2.5 items-center gap-3 hover:text-white hover:bg-white/5 transition-colors w-full cursor-pointer"
        >
          <Download className="size-4" />
          Download Plan
        </button>
      </div>
    </aside>
  );
}

export default Sidebar;
